# Recording parameters
videoFolder: "A:/VNCMP/2025-06-09"
videoFilename: "0.mp4"
frameRate: 300
recTimeInSec: 600
chunkLengthInSec: 60

# Camera parameters
numCams: 3
cameraSelection: [0, 1, 2]
cameraNames: ["Camera0", "Camera1", "Camera2"]
cameraMake: "flir"
frameWidth: 720
frameHeight: 528

# Flir settings
cameraTrigger: "Line0"
bufferSize: 50000 # May need to set lower, definitely set lower for shorter videos
cameraExposureTimeInUs: 100
cameraGain: 35
disableGamma: True

# Compression parameters
gpuID: 0                              
gpuMake: "nvidia"                     # "nvidia", "amd", "intel"                  
codec: "h265"                         # "h264", "h265", or user-defined video codec
quality: 0                           # 0-55. Lower number is less compression and larger files.
# qualityMode: "vbr"                    # "vbr" (variable bit rate), "cbr" (constant bit rate), or constqp
ffmpegLogLevel: "quiet"                # "quiet", "warning", "info"
preset: "fast"                        # How much effort should be put into reducing file size?
ffmpegPath: "C:/Users/lwood39/Documents/campy/ffmpeg-2024-03-11-git-3d1860ec8d-full_build/bin/ffmpeg"       # Location of ffmpeg binary if not using Anaconda
pixelFormatInput: "gray"
pixelFormatOutput: "rgb0"

# Display parameters
# displayFrameCounter: 1
# displayFrameRate: 5

# Trigger Parameters
# NOTE: This experiment is meant to be run with arduino on trigger_manual_control
# This means pins 2 and 3 are reserved
startArduino: True
serialPort: "COM3"                    # e.g. "COM3" Win; "/dev/ttyACM0" Linux
digitalPins: [12]
cameraDebug: True